#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Install S6 Overlay.
#======================================================================================================================

install () {

    # get file
    FILE=s6-overlay-${1}.tar.xz

    # check integrity
    sha256sum -cs ${FILE}.sha256 \
        || bf-error " .. S6 Overlay download does not match checksum."

    # extract
    bf-echo " .. extracting ${FILE}..."
    tar -C / -Jxpf ${FILE} \
        || bf-error " .. unable to extract ${FILE}."

}

bf-echo "Installing S6 Overlay..."
cd /s6
ARCH=`cat arch`
install "noarch"
install ${ARCH}
bf-done


#======================================================================================================================
# Cleanup.
#======================================================================================================================

bf-echo "Removing installation files..."
rm -rf /s6
bf-done
