#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Ensure target platform is set.
#======================================================================================================================

[[ -z "${TARGETPLATFORM-}" ]] && bf-error "Target platform not set."


#======================================================================================================================
# Get correct installer for target platform.
#======================================================================================================================

case "${TARGETPLATFORM}" in

    linux/amd64)
        ARCH="x86_64"
        ;;

    linux/arm/v7)
        ARCH="armhf"
        ;;

    linux/arm64)
        ARCH="aarch64"
        ;;

    *)
        bf-error "Unsupported target platform: ${TARGETPLATFORM}."
        ;;

esac

bf-echo "Platform architecture ${ARCH}."


#======================================================================================================================
# Get S6 Overlay version.
#======================================================================================================================

cd /tmp

S6_VERSION=$(cat S6_VERSION)
bf-echo "S6 Overlay version ${S6_VERSION}."


#======================================================================================================================
# Download and install S6 Overlay.
#======================================================================================================================

install () {

    # build filename - argument 1 is the architecture
    FILE="s6-overlay-${1}.tar.xz"

    # download file
    URL="https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/${FILE}"
    bf-echo " .. downloading ${URL}..."
    wget ${URL}

    # check integrity
    wget ${URL}.sha256
    sha256sum -cs ${FILE}.sha256 \
        || bf-error " .. S6 Overlay download does not match checksum."

    # extract
    bf-echo " .. extracting ${FILE}..."
    tar -C / -Jxpf ${FILE} \
        || bf-error " .. unable to extract ${FILE}."

}

bf-echo "Installing S6 Overlay v${S6_VERSION}..."
install "noarch"
install ${ARCH}
bf-done


#======================================================================================================================
# Cleanup.
#======================================================================================================================

bf-echo "Removing .empty files..."
rm /etc/periodic/1min/.empty
bf-done
