#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

bf-env "BF_IMAGE" `cat /BF_IMAGE`
bf-env "BF_VERSION" `cat /BF_VERSION`

bf-env "BF_BIN" "${BF_BIN}"

bf-env "BF_LIB" "${BF_LIB}"
bf-env "BF_INC" "${BF_LIB}/inc"

ETC=/etc/bf
bf-env "BF_CH_D" "${ETC}/ch.d"
bf-env "BF_INIT_D" "${ETC}/init.d"
bf-env "BF_TEMPLATES" "${ETC}/templates"
bf-env "BF_SRC" "${ETC}/src"

bf-env "BF_CRON_LOG_FILE" "/var/log/cron.log"

bf-env "S6_SERVICES" "/run/s6-rc/servicedirs"
