#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Start cron daemon.
#
# Crond flags
#   -f  run in foreground mode (allows S6 to supervise the service - which keeps the container running)
#   -l  log level (from 0 to 8 - 0 is the most verbose)
#   -L  log to a file (instead of stdout)
#======================================================================================================================

bf-echo "Starting cron."
/usr/sbin/crond \
    -f \
    -l ${BF_CRON_LOG_LEVEL} \
    -L ${BF_CRON_LOG_FILE}
