#!/command/with-contenv bash

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Start cron daemon.
#
# Crond flags
#   -n  run in foreground mode (allows S6 to supervise the service - which keeps the container running)
#======================================================================================================================

bf-echo "Starting cron."
/usr/sbin/cron -n
