name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        debian: [ "12" ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read Debian name
        uses: bfren/read-file@v2
        with:
          file: ./${{ matrix.debian }}/DEBIAN_NAME
        id: debian_name
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.debian }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_PUBLISHING=1
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/debian-s6:debian${{ matrix.debian }}
            bfren/debian-s6:debian${{ matrix.debian }}-${{ steps.version_major.outputs.contents }}
            bfren/debian-s6:debian${{ matrix.debian }}-${{ steps.version_minor.outputs.contents }}
            bfren/debian-s6:debian${{ matrix.debian }}-${{ steps.version.outputs.contents }}
            bfren/debian-s6:debian${{ steps.debian_minor.outputs.contents }}
            bfren/debian-s6:debian${{ steps.debian_minor.outputs.contents }}-${{ steps.version.outputs.contents }}
            bfren/debian-s6:${{ steps.debian_name.outputs.contents }}
            bfren/debian-s6:${{ steps.debian_name.outputs.contents }}-${{ steps.version_major.outputs.contents }}
            bfren/debian-s6:${{ steps.debian_name.outputs.contents }}-${{ steps.version_minor.outputs.contents }}
            bfren/debian-s6:${{ steps.debian_name.outputs.contents }}-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/debian-s6:debian${{ matrix.debian }}
            ghcr.io/bfren/debian-s6:debian${{ matrix.debian }}-${{ steps.version_major.outputs.contents }}
            ghcr.io/bfren/debian-s6:debian${{ matrix.debian }}-${{ steps.version_minor.outputs.contents }}
            ghcr.io/bfren/debian-s6:debian${{ matrix.debian }}-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/debian-s6:debian${{ steps.debian_minor.outputs.contents }}
            ghcr.io/bfren/debian-s6:debian${{ steps.debian_minor.outputs.contents }}-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/debian-s6:${{ steps.debian_name.outputs.contents }}
            ghcr.io/bfren/debian-s6:${{ steps.debian_name.outputs.contents }}-${{ steps.version_major.outputs.contents }}
            ghcr.io/bfren/debian-s6:${{ steps.debian_name.outputs.contents }}-${{ steps.version_minor.outputs.contents }}
            ghcr.io/bfren/debian-s6:${{ steps.debian_name.outputs.contents }}-${{ steps.version.outputs.contents }}
      -
        name: Build and push default tags
        id: docker_build_default
        uses: docker/build-push-action@v6
        if: matrix.debian == '12'
        with:
          context: .
          file: ./${{ matrix.debian }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_PUBLISHING=1
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/debian-s6:latest
            bfren/debian-s6:${{ steps.version_major.outputs.contents }}
            bfren/debian-s6:${{ steps.version_minor.outputs.contents }}
            bfren/debian-s6:${{ steps.version.outputs.contents }}
            ghcr.io/bfren/debian-s6:latest
            ghcr.io/bfren/debian-s6:${{ steps.version_major.outputs.contents }}
            ghcr.io/bfren/debian-s6:${{ steps.version_minor.outputs.contents }}
            ghcr.io/bfren/debian-s6:${{ steps.version.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
